// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import "github.com/jackc/pgx/v5/pgtype"

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type Category struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatorID int64  `json:"creator_id"`
}

type Expense struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CategoryID  int64              `json:"category_id"`
	SpentOn     pgtype.Timestamptz `json:"spent_on"`
}

type Income struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CategoryID  int64              `json:"category_id"`
	ReceivedOn  pgtype.Timestamptz `json:"received_on"`
}
