// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatorID int64  `json:"creator_id"`
	Emoji     string `json:"emoji"`
	Type      string `json:"type"`
}

type Expense struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CategoryID  int64              `json:"category_id"`
	SpentOn     pgtype.Timestamptz `json:"spent_on"`
}

type Income struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CategoryID  int64              `json:"category_id"`
	ReceivedOn  pgtype.Timestamptz `json:"received_on"`
}

type PeriodicExpense struct {
	ID                int64              `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Amount            float64            `json:"amount"`
	UserID            int64              `json:"user_id"`
	CategoryID        int64              `json:"category_id"`
	PeriodInterval    int32              `json:"period_interval"`
	PeriodUnit        string             `json:"period_unit"`
	StartDate         pgtype.Timestamptz `json:"start_date"`
	LastGeneratedDate pgtype.Timestamptz `json:"last_generated_date"`
	NextDueDate       pgtype.Timestamptz `json:"next_due_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                   int64  `json:"id"`
	Username             string `json:"username"`
	Password             string `json:"password"`
	SessionDurationHours int32  `json:"session_duration_hours"`
}
