// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, creator_id)
VALUES ($1, $2)
RETURNING id, name, creator_id
`

type CreateCategoryParams struct {
	Name      string `json:"name"`
	CreatorID int64  `json:"creator_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.CreatorID)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatorID)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  name, description, amount, user_id, category_id, spent_on
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, amount, user_id, created_at, category_id, spent_on
`

type CreateExpenseParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	SpentOn     pgtype.Timestamptz `json:"spent_on"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.UserID,
		arg.CategoryID,
		arg.SpentOn,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.SpentOn,
	)
	return i, err
}

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (
  name, description, amount, user_id, category_id, received_on
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, amount, user_id, created_at, category_id, received_on
`

type CreateIncomeParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	ReceivedOn  pgtype.Timestamptz `json:"received_on"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.UserID,
		arg.CategoryID,
		arg.ReceivedOn,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.ReceivedOn,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING id, username, password
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT
  id, name, creator_id
FROM
  categories
WHERE
  id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatorID)
	return i, err
}

const findCategoryByIDAndCreatorID = `-- name: FindCategoryByIDAndCreatorID :one
SELECT
  id, name, creator_id
FROM
  categories
WHERE
  id = $1 AND creator_id = $2
`

type FindCategoryByIDAndCreatorIDParams struct {
	ID        int64 `json:"id"`
	CreatorID int64 `json:"creator_id"`
}

func (q *Queries) FindCategoryByIDAndCreatorID(ctx context.Context, arg FindCategoryByIDAndCreatorIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByIDAndCreatorID, arg.ID, arg.CreatorID)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatorID)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT
  id, username, password
FROM
  users
WHERE
  id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT
  id, username, password
FROM
  users
WHERE
  username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
  id, name, creator_id
FROM
  categories
ORDER BY
  id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByCreatorID = `-- name: ListCategoriesByCreatorID :many
SELECT
  id, name, creator_id
FROM
  categories
WHERE
  creator_id = $1
ORDER BY
  id
`

func (q *Queries) ListCategoriesByCreatorID(ctx context.Context, creatorID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByCreatorID, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, spent_on
FROM
  expenses
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.SpentOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUserID = `-- name: ListExpensesByUserID :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, spent_on
FROM
  expenses
WHERE
  user_id = $1
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListExpensesByUserID(ctx context.Context, userID int64) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.SpentOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomes = `-- name: ListIncomes :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, received_on
FROM
  incomes
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ReceivedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByUserID = `-- name: ListIncomesByUserID :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, received_on
FROM
  incomes
WHERE
  user_id = $1
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListIncomesByUserID(ctx context.Context, userID int64) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ReceivedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, username, password
FROM
  users
ORDER BY
  id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
