// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, creator_id, emoji, type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, creator_id, emoji, type
`

type CreateCategoryParams struct {
	Name      string `json:"name"`
	CreatorID int64  `json:"creator_id"`
	Emoji     string `json:"emoji"`
	Type      string `json:"type"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.CreatorID,
		arg.Emoji,
		arg.Type,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.Emoji,
		&i.Type,
	)
	return i, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  name, description, amount, user_id, category_id, spent_on
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, amount, user_id, created_at, category_id, spent_on
`

type CreateExpenseParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	SpentOn     pgtype.Timestamptz `json:"spent_on"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.UserID,
		arg.CategoryID,
		arg.SpentOn,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.SpentOn,
	)
	return i, err
}

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (
  name, description, amount, user_id, category_id, received_on
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, amount, user_id, created_at, category_id, received_on
`

type CreateIncomeParams struct {
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	UserID      int64              `json:"user_id"`
	CategoryID  int64              `json:"category_id"`
	ReceivedOn  pgtype.Timestamptz `json:"received_on"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.UserID,
		arg.CategoryID,
		arg.ReceivedOn,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.ReceivedOn,
	)
	return i, err
}

const createPeriodicExpense = `-- name: CreatePeriodicExpense :one
INSERT INTO periodic_expenses (
  name, description, amount, user_id, category_id, period_interval, period_unit, start_date, next_due_date
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, description, amount, user_id, category_id, period_interval, period_unit, start_date, last_generated_date, next_due_date, created_at
`

type CreatePeriodicExpenseParams struct {
	Name           string             `json:"name"`
	Description    string             `json:"description"`
	Amount         float64            `json:"amount"`
	UserID         int64              `json:"user_id"`
	CategoryID     int64              `json:"category_id"`
	PeriodInterval int32              `json:"period_interval"`
	PeriodUnit     string             `json:"period_unit"`
	StartDate      pgtype.Timestamptz `json:"start_date"`
	NextDueDate    pgtype.Timestamptz `json:"next_due_date"`
}

func (q *Queries) CreatePeriodicExpense(ctx context.Context, arg CreatePeriodicExpenseParams) (PeriodicExpense, error) {
	row := q.db.QueryRow(ctx, createPeriodicExpense,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.UserID,
		arg.CategoryID,
		arg.PeriodInterval,
		arg.PeriodUnit,
		arg.StartDate,
		arg.NextDueDate,
	)
	var i PeriodicExpense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CategoryID,
		&i.PeriodInterval,
		&i.PeriodUnit,
		&i.StartDate,
		&i.LastGeneratedDate,
		&i.NextDueDate,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING id, username, password
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const deletePeriodicExpense = `-- name: DeletePeriodicExpense :exec
DELETE FROM periodic_expenses
WHERE id = $1 AND user_id = $2
`

type DeletePeriodicExpenseParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePeriodicExpense(ctx context.Context, arg DeletePeriodicExpenseParams) error {
	_, err := q.db.Exec(ctx, deletePeriodicExpense, arg.ID, arg.UserID)
	return err
}

const findCategoryByID = `-- name: FindCategoryByID :one
SELECT
  id, name, creator_id, emoji, type
FROM
  categories
WHERE
  id = $1
`

func (q *Queries) FindCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.Emoji,
		&i.Type,
	)
	return i, err
}

const findCategoryByIDAndCreatorID = `-- name: FindCategoryByIDAndCreatorID :one
SELECT
  id, name, creator_id, emoji, type
FROM
  categories
WHERE
  id = $1 AND creator_id = $2
`

type FindCategoryByIDAndCreatorIDParams struct {
	ID        int64 `json:"id"`
	CreatorID int64 `json:"creator_id"`
}

func (q *Queries) FindCategoryByIDAndCreatorID(ctx context.Context, arg FindCategoryByIDAndCreatorIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, findCategoryByIDAndCreatorID, arg.ID, arg.CreatorID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.Emoji,
		&i.Type,
	)
	return i, err
}

const findDuePeriodicExpensesByUserID = `-- name: FindDuePeriodicExpensesByUserID :many
SELECT
  id, name, description, amount, user_id, category_id, period_interval, period_unit, start_date, last_generated_date, next_due_date, created_at
FROM
  periodic_expenses
WHERE
  user_id = $1 AND next_due_date <= now()
`

func (q *Queries) FindDuePeriodicExpensesByUserID(ctx context.Context, userID int64) ([]PeriodicExpense, error) {
	rows, err := q.db.Query(ctx, findDuePeriodicExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicExpense
	for rows.Next() {
		var i PeriodicExpense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CategoryID,
			&i.PeriodInterval,
			&i.PeriodUnit,
			&i.StartDate,
			&i.LastGeneratedDate,
			&i.NextDueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByID = `-- name: FindUserByID :one
SELECT
  id, username, password
FROM
  users
WHERE
  id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT
  id, username, password
FROM
  users
WHERE
  username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
  id, name, creator_id, emoji, type
FROM
  categories
ORDER BY
  id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatorID,
			&i.Emoji,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByCreatorID = `-- name: ListCategoriesByCreatorID :many
SELECT
  id, name, creator_id, emoji, type
FROM
  categories
WHERE
  creator_id = $1
ORDER BY
  id
`

func (q *Queries) ListCategoriesByCreatorID(ctx context.Context, creatorID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByCreatorID, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatorID,
			&i.Emoji,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, spent_on
FROM
  expenses
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.SpentOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByUserID = `-- name: ListExpensesByUserID :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, spent_on
FROM
  expenses
WHERE
  user_id = $1
ORDER BY
  created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListExpensesByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListExpensesByUserID(ctx context.Context, arg ListExpensesByUserIDParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.SpentOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomes = `-- name: ListIncomes :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, received_on
FROM
  incomes
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListIncomes(ctx context.Context) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ReceivedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomesByUserID = `-- name: ListIncomesByUserID :many
SELECT
  id, name, description, amount, user_id, created_at, category_id, received_on
FROM
  incomes
WHERE
  user_id = $1
ORDER BY
  created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListIncomesByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIncomesByUserID(ctx context.Context, arg ListIncomesByUserIDParams) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CreatedAt,
			&i.CategoryID,
			&i.ReceivedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodicExpensesByUserID = `-- name: ListPeriodicExpensesByUserID :many
SELECT
  id, name, description, amount, user_id, category_id, period_interval, period_unit, start_date, last_generated_date, next_due_date, created_at
FROM
  periodic_expenses
WHERE
  user_id = $1
ORDER BY
  created_at DESC, id DESC
`

func (q *Queries) ListPeriodicExpensesByUserID(ctx context.Context, userID int64) ([]PeriodicExpense, error) {
	rows, err := q.db.Query(ctx, listPeriodicExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodicExpense
	for rows.Next() {
		var i PeriodicExpense
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Amount,
			&i.UserID,
			&i.CategoryID,
			&i.PeriodInterval,
			&i.PeriodUnit,
			&i.StartDate,
			&i.LastGeneratedDate,
			&i.NextDueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, username, password
FROM
  users
ORDER BY
  id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET
  name = $2,
  emoji = $3,
  type = $4
WHERE
  id = $1 AND creator_id = $5
RETURNING id, name, creator_id, emoji, type
`

type UpdateCategoryParams struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Emoji     string `json:"emoji"`
	Type      string `json:"type"`
	CreatorID int64  `json:"creator_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Emoji,
		arg.Type,
		arg.CreatorID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatorID,
		&i.Emoji,
		&i.Type,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET
  name = $2,
  description = $3,
  amount = $4,
  category_id = $5,
  spent_on = $6
WHERE
  id = $1 AND user_id = $7
RETURNING id, name, description, amount, user_id, created_at, category_id, spent_on
`

type UpdateExpenseParams struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	CategoryID  int64              `json:"category_id"`
	SpentOn     pgtype.Timestamptz `json:"spent_on"`
	UserID      int64              `json:"user_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.CategoryID,
		arg.SpentOn,
		arg.UserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.SpentOn,
	)
	return i, err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes
SET
  name = $2,
  description = $3,
  amount = $4,
  category_id = $5,
  received_on = $6
WHERE
  id = $1 AND user_id = $7
RETURNING id, name, description, amount, user_id, created_at, category_id, received_on
`

type UpdateIncomeParams struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Amount      float64            `json:"amount"`
	CategoryID  int64              `json:"category_id"`
	ReceivedOn  pgtype.Timestamptz `json:"received_on"`
	UserID      int64              `json:"user_id"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Amount,
		arg.CategoryID,
		arg.ReceivedOn,
		arg.UserID,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Amount,
		&i.UserID,
		&i.CreatedAt,
		&i.CategoryID,
		&i.ReceivedOn,
	)
	return i, err
}

const updatePeriodicExpenseNextDueDate = `-- name: UpdatePeriodicExpenseNextDueDate :exec
UPDATE periodic_expenses
SET
  last_generated_date = $2,
  next_due_date = $3
WHERE
  id = $1
`

type UpdatePeriodicExpenseNextDueDateParams struct {
	ID                int64              `json:"id"`
	LastGeneratedDate pgtype.Timestamptz `json:"last_generated_date"`
	NextDueDate       pgtype.Timestamptz `json:"next_due_date"`
}

func (q *Queries) UpdatePeriodicExpenseNextDueDate(ctx context.Context, arg UpdatePeriodicExpenseNextDueDateParams) error {
	_, err := q.db.Exec(ctx, updatePeriodicExpenseNextDueDate, arg.ID, arg.LastGeneratedDate, arg.NextDueDate)
	return err
}
