site_name: GoTrackMoney
site_description: Documentation for GoTrackMoney - A self-hosted personal finance tracker
site_author: Gabe

theme: readthedocs

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Guides:
    - Backup & Restore: backup_restore.md
    - Data Porting: porting.md
    - Testing: tests.md
  - Implementation:
    - Periodic Expenses: periodic_expenses_implementation.md
